### ISSUE TITLE
核显UHD630驱动

### ISSUE THREAD

**Issue by besmart1874** [qianqiangliu/MSI-Z390I-Hackintosh-OpenCore#1]
请问我只有核显UHD630，其他的配置跟您是一样的。我能使用这个EFI文件吗？

**Comment by qianqiangliu** [comment]
把 **AAPL,ig-platform-id** 修改为 **07009B3E** 即可。

**Comment by besmart1874** [comment]
修改完成后，我的PCIE插槽里面插着一张1660Super，我可以不用管它嘛！还是应该去做屏蔽！

**Comment by qianqiangliu** [comment]
建议屏蔽。
